all: teste1 teste2 teste3 teste4 teste5 teste6

teste1:
	gcc -o teste1 teste1.c -L../lib/  -luthread -w

teste2:
	gcc -o teste2 teste2.c -L../lib/  -luthread -w

teste3:
	gcc -o teste3 teste3.c -L../lib/  -luthread -w

teste4:
	gcc -o teste4 teste4.c -L../lib/  -luthread -w

teste5:
	gcc -o teste5 teste5.c -L../lib/  -luthread -w

teste6:
	gcc -o teste6 teste6.c -L../lib/  -luthread -w

clean:
	rm -rf teste1 teste2 teste3 teste4 teste5 teste6
